@echo off
title Installing Steam Analyzer script...

echo Creating VirtualEnv directory...
virtualenv.exe SteamAnalyzerVenv\
echo Upgrading pip...
.\SteamAnalyzerVenv\Scripts\python.exe -m pip install --upgrade pip
echo Installing dependencies...
.\SteamAnalyzerVenv\Scripts\pip.exe install bs4
.\SteamAnalyzerVenv\Scripts\pip.exe install lxml
.\SteamAnalyzerVenv\Scripts\pip.exe install requests
